"""TEST_TOOL TOOL — generated by AiGenie Hub for tenant `acme`.

EDIT ONLY   : run() between the >>> markers.
DO NOT TOUCH: the register() call at the bottom (that's how agents find this tool).
TEST        : python -m pytest tests/test_test_tool_tool.py
REGENERATE  : changing forms in the Hub regenerates this file; your
              edits inside the >>> markers are yours to re-apply, so
              keep business logic small and factored.
"""

from .base import BaseTool, register


class TestToolTool(BaseTool):
    """test_tool

    Called by agents as: self.tools.call("test_tool", **kwargs)
    """

    name = "test_tool"

    def run(self, **kwargs) -> dict:
        # >>> YOUR BUSINESS LOGIC — call your API/DB and return a plain dict
        return {"ok": True, "echo": kwargs}
        # <<<


register(TestToolTool())
