"""REQUEST ADAPTER — generated by AiGenie Hub for tenant `acmehealth`.

EDIT ONLY   : the TODO lines mapping your event fields.
DO NOT TOUCH: the GatewayRequest construction (wire contract).
TEST        : python -m pytest tests/test_adapter.py
REGENERATE  : changing forms in the Hub regenerates this file; your
              edits inside the >>> markers are yours to re-apply, so
              keep business logic small and factored.
"""

from aigenie_sdk import EntityLink, GatewayRequest

from .field_selector import SELECTOR


def adapt_request(event: dict) -> GatewayRequest:
    payload = event.get("payload", event)
    entity_ref = str(payload.get("member_id", "") or "")
    return GatewayRequest(
        query=str(payload.get("query", "")),
        user_id=str(payload.get("user_id", "")),
        session_id=str(payload.get("session_id", "")),
        source="acmehealth",
        entity_link=EntityLink(entity_ref=entity_ref,
                               entity_scope="acmehealth")
        if entity_ref else None,
        field_selector=SELECTOR,
        onboarding_answers=payload.get("onboarding_answers", []),
    )
