"""AIGENIE GATEWAY CLIENT — generated by AiGenie Hub for tenant `acmehealth`.

EDIT ONLY   : AIGENIE_GATEWAY_URL / auth via environment only.
DO NOT TOUCH: the request/response handling.
TEST        : covered by tests/test_master_agent.py
REGENERATE  : changing forms in the Hub regenerates this file; your
              edits inside the >>> markers are yours to re-apply, so
              keep business logic small and factored.
"""

import json
import os
import urllib.request

from aigenie_sdk import GatewayRequest

AIGENIE_GATEWAY_URL = os.getenv("AIGENIE_GATEWAY_URL", "http://127.0.0.1:9000/gateway/acmehealth/invoke")
AIGENIE_GATEWAY_TOKEN = os.getenv("AIGENIE_GATEWAY_TOKEN", "")


def call_aigenie(request: GatewayRequest) -> dict:
    body = {"payload": request.model_dump(mode="json")}
    if AIGENIE_GATEWAY_TOKEN:
        body["auth_token"] = AIGENIE_GATEWAY_TOKEN
    http_req = urllib.request.Request(
        AIGENIE_GATEWAY_URL, data=json.dumps(body).encode(),
        headers={"Content-Type": "application/json"})
    with urllib.request.urlopen(http_req) as resp:
        return json.loads(resp.read())
