"""MASTER AGENT (customer-side orchestrator) — generated by AiGenie Hub for tenant `acmehealth`.

EDIT ONLY   : ROUTING_TABLE, GOAL and the merge logic between the >>> markers.
DO NOT TOUCH: call_aigenie() and the wire constants — they speak the AiGenie contract.
TEST        : python -m pytest tests/test_master_agent.py
REGENERATE  : changing forms in the Hub regenerates this file; your
              edits inside the >>> markers are yours to re-apply, so
              keep business logic small and factored.
"""

import json
import os
import time
import urllib.request

from .adapter import adapt_request
from .agents.base import run_agent

# ── GOAL ──────────────────────────────────────────────────────────────────
# Route every user turn to the best executor and return one merged response.
# While AIGENIE_ENABLED is true, EVERY turn goes to AiGenie — it holds
# memory, persona, guardrails, intent classification and the LLM budget,
# and already dispatches to YOUR OWN agents/tools (via its custom_agent
# strategy) with all of that context attached. This file does not
# re-implement that routing; it only forwards.
#
# ROUTING_TABLE below is NOT a normal-operation feature — it is your
# EXIT PATH. It is only consulted when AIGENIE_ENABLED=false (you have
# left AiGenie) or a call to AiGenie fails (degraded/unreachable this
# turn). At those two moments this master agent keeps your custom agents
# running standalone, with no AiGenie service involved.
#
# EXIT STRATEGY — this workspace is also your way OUT of AiGenie:
# agents/ and tools/ are stdlib-only Python; the adapter layer uses only
# aigenie-sdk's open pydantic models (data shapes, no platform code).
# What you lose without AiGenie: memory-enriched context & persona,
# relationship/ontology awareness, guardrail enforcement, intent
# classification, observability dashboards, quality tuning — and your
# LLM cost is likely to RISE, because AiGenie's 0-LLM deterministic paths
# (emergency, clarify, rule-based answers) collapse into real LLM calls
# once you route them yourself via handle_without_aigenie(). Before you
# flip AIGENIE_ENABLED, pull a concrete, numbers-based breakdown for YOUR
# tenant — hub action "master_agent.exit_impact" (also on the Hub's
# Master Agent page) — rather than relying on this general description.
# What you keep regardless: this orchestrator, agents/, tools/, adapter,
# field selector — all of it, yours, no platform code inside any of them.

# ── AiGenie wire contract (configured in the Hub → Master Agent page) ────
AIGENIE_ENABLED = os.getenv("AIGENIE_ENABLED", "true").lower() != "false"
AIGENIE_URL = os.getenv("AIGENIE_GATEWAY_URL", "http://127.0.0.1:9000/gateway/acmehealth/invoke")
AUTH_HEADER = "x-auth-token"
TOKEN_ENV = "AIGENIE_GATEWAY_TOKEN"          # export this env var with your gateway token
TIMEOUT_SECONDS = 30
RETRIES = 1
FALLBACK_TEXT = 'Sorry — I could not reach the assistant. Please try again.'

# Your app's field → AiGenie GatewayRequest field:
PAYLOAD_MAP = {
    "query": "query",
    "user_id": "user_id",
    "session_id": "session_id",
}

# Exit-path routing only (see GOAL above) — first match wins, target must
# be an agent registered in agents/. Never consulted while connected.
ROUTING_TABLE = [
    # ("keyword or intent", "<agent_name>"),
]


def call_aigenie(request) -> dict:
    body = {"payload": request.model_dump(mode="json")}
    token = os.getenv(TOKEN_ENV, "")
    if token:
        body["auth_token"] = token
    data = json.dumps(body).encode()
    last_error = None
    for _ in range(RETRIES + 1):
        try:
            http_req = urllib.request.Request(
                AIGENIE_URL, data=data,
                headers={"Content-Type": "application/json",
                          **({AUTH_HEADER: token} if token else {})})
            with urllib.request.urlopen(http_req, timeout=TIMEOUT_SECONDS) as resp:
                return json.loads(resp.read())
        except Exception as exc:            # noqa: BLE001 — retry then fall back
            last_error = exc
            time.sleep(0.5)
    return {"success": False, "response_text": FALLBACK_TEXT,
             "error": {"message": str(last_error)}}


def handle_without_aigenie(request) -> dict:
    """Standalone fallback for turns your ROUTING_TABLE doesn't cover when
    AiGenie is disabled. Wire your own LLM or rules here after exit."""
    # >>> YOUR STANDALONE FALLBACK
    return {"success": True, "response_text":
             "This request needs a human agent right now — we'll follow up.",
             "cards": []}
    # <<<


def handle(event: dict) -> dict:
    request = adapt_request(event)
    if AIGENIE_ENABLED:
        result = call_aigenie(request)
        if result.get("success", True):
            return result
        # AiGenie unreachable this turn — degrade to exit-path routing below
    # >>> YOUR EXIT-PATH ROUTING — only reached when AiGenie is disabled or
    # unreachable (see ROUTING_TABLE comment above). Replace/extend as needed.
    text = request.query.lower()
    for match, target in ROUTING_TABLE:
        # "aigenie" is a legacy target value from routing configs saved
        # before this exit-path redesign — meaningless now that
        # AIGENIE_ENABLED already governs that above; skip, don't crash.
        if match and match in text and target != "aigenie":
            return run_agent(target, request)
    # <<<
    return handle_without_aigenie(request)
