"""RESPONSE MAPPER — generated by AiGenie Hub for tenant `acmehealth`.

EDIT ONLY   : map_response() — turn generic cards into YOUR UI JSON.
DO NOT TOUCH: nothing else; this file is all yours.
TEST        : python -m pytest tests/test_response_mapper.py
REGENERATE  : changing forms in the Hub regenerates this file; your
              edits inside the >>> markers are yours to re-apply, so
              keep business logic small and factored.
"""


def map_response(gateway_response: dict) -> dict:
    """gateway_response is a GatewayResponse dict: response_text, cards
    (each with schema_id + payload), onboarding_questions, profile_question,
    profile_completeness, active_flow...

    # >>> YOUR UI SHAPE — map card schema_ids to your widgets:
    #   "acmehealth.coverage.v1" -> shape it like your UI expects
    #   "acmehealth.coverage.v1" -> shape it like your UI expects

    # <<<
    """
    return {
        "message": gateway_response.get("response_text", ""),
        "cards": gateway_response.get("cards", []),
        "questions": gateway_response.get("onboarding_questions", []),
        "profile_question": gateway_response.get("profile_question"),
        "profile_completeness": gateway_response.get("profile_completeness"),
        "session_id": gateway_response.get("session_id", ""),
        "user_id": gateway_response.get("user_id", ""),
    }
