"""AGENT/TOOL RUNTIME (shared) — generated by AiGenie Hub for tenant `acmehealth`.

EDIT ONLY   : nothing — regenerated verbatim.
DO NOT TOUCH: everything.
TEST        : covered by each agent's test
REGENERATE  : changing forms in the Hub regenerates this file; your
              edits inside the >>> markers are yours to re-apply, so
              keep business logic small and factored.
"""

from dataclasses import dataclass, field


@dataclass
class AgentRequest:
    query: str = ""
    slots: dict = field(default_factory=dict)
    profile: dict = field(default_factory=dict)
    history: list = field(default_factory=list)   # recent turns [{role, content}]
    summary: str = ""                             # older-context summary
    knowledge: dict = field(default_factory=dict) # 1-hop graph slice: labels +
                                                  # explicitly published attrs
    entity_ref: str = ""                           # the source record this call
                                                  # concerns (write-back agents)
    assigned_model: dict = field(default_factory=dict)  # {} unless a Model
                                                  # Profile is pinned to this
                                                  # agent's intent in the Hub
                                                  # (App Onboarding Step 3) —
                                                  # then {"model": "...",
                                                  # "base_url": "..."} (never
                                                  # a key/secret — bring your
                                                  # own the way you already do)


_TOOLS: dict[str, "BaseTool"] = {}
_AGENTS: dict[str, "BaseCustomAgent"] = {}


class BaseTool:
    name = ""

    def run(self, **kwargs) -> dict:
        raise NotImplementedError


def register(tool: BaseTool) -> None:
    _TOOLS[tool.name] = tool


def _load_tools() -> None:
    """Imports the sibling tools package (whose __init__ imports every
    *_tool.py, each of which register()s itself) — lazily, on first call,
    so agents never need to import tools explicitly."""
    import importlib
    workspace = __package__.rsplit(".", 1)[0]
    try:
        importlib.import_module(f"{workspace}.tools")
    except ModuleNotFoundError:
        pass


class _ToolBox:
    def call(self, name: str, **kwargs) -> dict:
        if name not in _TOOLS:
            _load_tools()
        tool = _TOOLS.get(name)
        if tool is None:
            return {"ok": False, "error": f"tool {name!r} is not registered"}
        return tool.run(**kwargs)


@dataclass
class AgentResult:
    text: str
    card_schema_id: str = ""
    card: dict = field(default_factory=dict)

    def to_response(self) -> dict:
        cards = [{"schema_id": self.card_schema_id, "payload": self.card}] \
            if self.card_schema_id else []
        return {"message": self.text, "cards": cards}


class BaseCustomAgent:
    intent = ""
    card_schema_id = ""
    tools = _ToolBox()

    def __init_subclass__(cls, **kwargs):
        super().__init_subclass__(**kwargs)
        _AGENTS[cls.__name__] = None  # instantiated lazily by run_agent

    def result(self, text: str, card_kwargs: dict | None = None) -> AgentResult:
        return AgentResult(text=text, card_schema_id=self.card_schema_id,
                           card=card_kwargs or {})

    def execute(self, request: AgentRequest) -> AgentResult:
        raise NotImplementedError


def run_agent(name: str, request) -> dict:
    """Locate <name>_agent.py's class, run it, return a UI-ready dict."""
    import importlib
    module = importlib.import_module(f".{name}_agent", package=__package__)
    class_name = "".join(w.capitalize() for w in name.split("_")) + "Agent"
    agent: BaseCustomAgent = getattr(module, class_name)()

    def _get(key, default):
        if isinstance(request, dict):
            return request.get(key, default)
        return getattr(request, key, default)

    slots = _get("slots", {}) or {}
    return agent.execute(AgentRequest(
        query=_get("query", "") or "", slots=slots,
        profile=_get("profile", {}) or {}, history=_get("history", []) or [],
        summary=_get("summary", "") or "",
        knowledge=_get("knowledge", {}) or {},
        entity_ref=_get("entity_ref", "") or "",
        assigned_model=slots.get("_aigenie_model", {}) or {})).to_response()
