"""PLAN_COVERAGE AGENT — generated by AiGenie Hub for tenant `acmehealth`.

EDIT ONLY   : execute() between the >>> markers.
DO NOT TOUCH: the request/response models and the card builder (wire contract).
TEST        : python -m pytest tests/test_plan_coverage_agent.py
REGENERATE  : changing forms in the Hub regenerates this file; your
              edits inside the >>> markers are yours to re-apply, so
              keep business logic small and factored.
"""

from .base import AgentRequest, AgentResult, BaseCustomAgent


class PlanCoverageAgent(BaseCustomAgent):
    """Handles the `plan_coverage` intent.

    request.query          : the end user's message
    request.slots          : parsed fields (from your master agent / adapter)
    request.profile        : the user's profile attributes (already privacy-projected)
    request.assigned_model : {} unless a Model Profile is pinned to this
                              intent in the Hub (App Onboarding Step 3) — then
                              {"model": "...", "base_url": "..."}. Identity
                              only, never a key/secret: call it with whatever
                              credential you already use for that provider,
                              same as before this existed.
    self.tools.call()      : invoke a registered tool by name; available tools:
        #   (no tools bound — add some in the Hub's Agent Registry)
    """

    intent = "plan_coverage"
    card_schema_id = "acmehealth.coverage.v1"

    def execute(self, request: AgentRequest) -> AgentResult:
        # >>> YOUR BUSINESS LOGIC — replace the sample below
        # if request.assigned_model:                                 # optional
        #     model = request.assigned_model.get("model")             # e.g. call
        #     base_url = request.assigned_model.get("base_url")       # your LLM
        #     ...                                                     # with these
        result_text = f"plan_coverage handled: {request.query}"
        # <<<
        return self.result(result_text, card_kwargs=dict(plan_tier="TODO", service="TODO", covered="TODO"))
